version: "3.8"

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: medic-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medic"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_ENV_VALIDATION=1
    container_name: medic-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/medic"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: medic-network
