name: Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      # Skip strict env validation during CI build
      SKIP_ENV_VALIDATION: 'true'
      NODE_ENV: production
      # Provide a dummy DB URL so env parsing doesn't fail. Build shouldn't connect.
      DATABASE_URL: 'postgres://user:pass@localhost:5432/ci'
      # Disable Next telemetry in CI
      NEXT_TELEMETRY_DISABLED: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: bun run build
